FORMAT: 1A
# Rails API Base

# Group Passwords

## Update Password [api/v1/users/password]

### Update [PUT]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: danuta@tremblay.name

    + Body

            {"password":"123456789","password_confirmation":""}

+ Response 422 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712945326
            uid: danuta@tremblay.name

    + Body

            {
              "success": false,
              "errors": {
                "password_confirmation": [
                  "doesn't match Password"
                ],
                "full_messages": [
                  "Password confirmation doesn't match Password"
                ]
              }
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: jose_carroll@yost.co

    + Body

            {"password":"123456789","password_confirmation":"123456789"}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712945326
            uid: jose_carroll@yost.co

    + Body

            {
              "success": true,
              "data": {
                "email": "jose_carroll@yost.co",
                "id": 1,
                "uid": "jose_carroll@yost.co",
                "allow_password_change": false,
                "first_name": "Mac Stoltenberg",
                "last_name": "Skiles",
                "username": "matt.ohara",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "created_at": "2022-04-12T18:08:45.991Z",
                "updated_at": "2022-04-12T18:08:46.188Z",
                "provider": "email"
              },
              "message": "Your password has been successfully updated."
            }

## Create Password [api/v1/users/password]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: jutta@ratke-spinka.io

    + Body

            {"email":"notvalid@example.com"}

+ Response 404 ()

    + Body

            {
              "error": "Unable to find user with email 'notvalid@example.com'."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: lincoln@kshlerin-konopelski.info

    + Body

            {"email":"lincoln@kshlerin-konopelski.info"}

+ Response 200 ()

    + Body

            {
              "success": true,
              "message": "An email has been sent to 'lincoln@kshlerin-konopelski.info' containing instructions for resetting your password."
            }

## Edit Password [api/v1/users/password/edit]

### Edit [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: mario_jast@durgan-bruen.co

+ Response 302 ()

    + Body

            <html><body>You are being <a href="http://localhost:3000?access-token=1234567890123456789012&amp;client=abcdefghijklmnopqrstuv&amp;client_id=abcdefghijklmnopqrstuv&amp;config=&amp;expiry=1712945326&amp;reset_password=true&amp;token=1234567890123456789012&amp;uid=mario_jast%40durgan-bruen.co">redirected</a>.</body></html>

# Group Sessions

## Session [api/v1/users/sign_in]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: tyrone_bogisich@lehner-spencer.io

    + Body

            {"user":{"email":"tyrone_bogisich@lehner-spencer.io","password":"wrong-password"},"format":"json"}

+ Response 401 ()

    + Body

            {
              "error": "Invalid login credentials. Please try again."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: chanda_towne@terry-stroman.org

    + Body

            {"user":{"email":"chanda_towne@terry-stroman.org","password":"3VkM90o3Ve7CsOzA"},"format":"json"}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712945328
            uid: chanda_towne@terry-stroman.org

    + Body

            {
              "user": {
                "id": 12,
                "email": "chanda_towne@terry-stroman.org",
                "name": "Lyle Hilll Daniel",
                "username": "alfonzo_daugherty",
                "first_name": "Lyle Hilll",
                "last_name": "Daniel",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "uid": "chanda_towne@terry-stroman.org",
                "provider": "email",
                "created_at": "2022-04-12T18:08:47.978Z",
                "updated_at": "2022-04-12T18:08:48.121Z"
              }
            }

## Session [api/v1/users/sign_out]

### Delete [DELETE]

+ Request Bad

    + Headers

            Access-Token: notvalidtoken
            Client: abcdefghijklmnopqrstuv
            Uid: stephan@collins-cormier.co

+ Response 404 ()

    + Body

            {
              "error": "User was not found or was not logged in."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: lindsay_kirlin@moen.org

+ Response 200 ()

    + Body

            {
              "success": true
            }

# Group Settings

## Must Update [api/v1/settings/must_update]

### Get [GET]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: wiley_wintheiser@herzog.name

+ Response 200 ()

    + Body

            {
              "must_update": true
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: florencia@shanahan.com

+ Response 200 ()

    + Body

            {
              "must_update": false
            }

# Group Status

## Status [api/v1/status]

### Get [GET]

+ Request Ok

+ Response 200 ()

    + Body

            {
              "online": true
            }

# Group Users

## Create User [api/v1/users]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: lynn.shanahan@green.com

    + Body

            {"user":{"email":"not-valid","password":"VjIaB0b2","username":"homer","first_name":"Dannette Kris","last_name":"Stroman","uid":"3073e0d9-d1da-4baf-879f-cb49abd60858"},"format":"json"}

+ Response 422 ()

    + Body

            {
              "status": "error",
              "data": {
                "id": null,
                "email": "not-valid",
                "allow_password_change": false,
                "first_name": "Dannette Kris",
                "last_name": "Stroman",
                "username": "homer",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "created_at": null,
                "updated_at": null,
                "provider": "email",
                "uid": "not-valid"
              },
              "errors": {
                "email": [
                  "is not an email"
                ],
                "full_messages": [
                  "Email is not an email"
                ]
              }
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: mia@mckenzie.info

    + Body

            {"user":{"email":"teodoro@hilll-boehm.org","password":"8Lz83E3fPhKvNeNs","username":"connie","first_name":"Moira Hayes","last_name":"Pagac","uid":"09601e67-9938-4c45-b36a-7d195d9893c4"},"format":"json"}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712945327
            uid: teodoro@hilll-boehm.org

    + Body

            {
              "user": {
                "id": 9,
                "email": "teodoro@hilll-boehm.org",
                "name": "Moira Hayes Pagac",
                "username": "connie",
                "first_name": "Moira Hayes",
                "last_name": "Pagac",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "uid": "teodoro@hilll-boehm.org",
                "provider": "email",
                "created_at": "2022-04-12T18:08:47.621Z",
                "updated_at": "2022-04-12T18:08:47.688Z"
              }
            }

## Show User [api/v1/user]

### Show [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: norma.thompson@buckridge.org

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712945327
            uid: norma.thompson@buckridge.org

    + Body

            {
              "user": {
                "id": 6,
                "email": "norma.thompson@buckridge.org",
                "name": "Vivienne Shields IV Nicolas",
                "username": "erwin",
                "first_name": "Vivienne Shields IV",
                "last_name": "Nicolas",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "uid": "norma.thompson@buckridge.org",
                "provider": "email",
                "created_at": "2022-04-12T18:08:47.246Z",
                "updated_at": "2022-04-12T18:08:47.304Z"
              }
            }

## Update User [api/v1/user]

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: sanora@cassin-langworth.net

    + Body

            {"user":{"username":"new username"}}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712945327
            uid: sanora@cassin-langworth.net

    + Body

            {
              "user": {
                "id": 10,
                "email": "sanora@cassin-langworth.net",
                "name": "Wanita Greenholt IV Bechtelar",
                "username": "new username",
                "first_name": "Wanita Greenholt IV",
                "last_name": "Bechtelar",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "uid": "sanora@cassin-langworth.net",
                "provider": "email",
                "created_at": "2022-04-12T18:08:47.722Z",
                "updated_at": "2022-04-12T18:08:47.866Z"
              }
            }
