FORMAT: 1A
# Rails API Base

# Group Passwords

## Update Password [api/v1/users/password]

### Update [PUT]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: bruno.terry@kovacek.net

    + Body

            {"password":"123456789","password_confirmation":""}

+ Response 422 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712940193
            uid: bruno.terry@kovacek.net

    + Body

            {
              "success": false,
              "errors": {
                "password_confirmation": [
                  "doesn't match Password"
                ],
                "full_messages": [
                  "Password confirmation doesn't match Password"
                ]
              }
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: phyllis@rath.com

    + Body

            {"password":"123456789","password_confirmation":"123456789"}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712940194
            uid: phyllis@rath.com

    + Body

            {
              "success": true,
              "data": {
                "email": "phyllis@rath.com",
                "id": 4,
                "uid": "phyllis@rath.com",
                "allow_password_change": false,
                "first_name": "Lamont Kilback",
                "last_name": "Braun",
                "username": "maritza",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "created_at": "2022-04-12T16:43:14.036Z",
                "updated_at": "2022-04-12T16:43:14.197Z",
                "provider": "email"
              },
              "message": "Your password has been successfully updated."
            }

## Create Password [api/v1/users/password]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: elvina@mayert-lynch.co

    + Body

            {"email":"notvalid@example.com"}

+ Response 404 ()

    + Body

            {
              "error": "Unable to find user with email 'notvalid@example.com'."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: bell@jacobson-johnson.net

    + Body

            {"email":"bell@jacobson-johnson.net"}

+ Response 200 ()

    + Body

            {
              "success": true,
              "message": "An email has been sent to 'bell@jacobson-johnson.net' containing instructions for resetting your password."
            }

## Edit Password [api/v1/users/password/edit]

### Edit [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: quintin@schumm.info

+ Response 302 ()

    + Body

            <html><body>You are being <a href="http://localhost:3000?access-token=1234567890123456789012&amp;client=abcdefghijklmnopqrstuv&amp;client_id=abcdefghijklmnopqrstuv&amp;config=&amp;expiry=1712940194&amp;reset_password=true&amp;token=1234567890123456789012&amp;uid=quintin%40schumm.info">redirected</a>.</body></html>

# Group Sessions

## Session [api/v1/users/sign_in]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: elbert@nolan.io

    + Body

            {"user":{"email":"elbert@nolan.io","password":"wrong-password"},"format":"json"}

+ Response 401 ()

    + Body

            {
              "error": "Invalid login credentials. Please try again."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: dewey_sawayn@sanford.org

    + Body

            {"user":{"email":"dewey_sawayn@sanford.org","password":"1I4lYi2D36iX"},"format":"json"}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712940195
            uid: dewey_sawayn@sanford.org

    + Body

            {
              "user": {
                "id": 9,
                "email": "dewey_sawayn@sanford.org",
                "name": "Antony Ullrich Swift",
                "username": "kena_dubuque",
                "first_name": "Antony Ullrich",
                "last_name": "Swift",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "uid": "dewey_sawayn@sanford.org",
                "provider": "email",
                "created_at": "2022-04-12T16:43:14.949Z",
                "updated_at": "2022-04-12T16:43:15.104Z"
              }
            }

## Session [api/v1/users/sign_out]

### Delete [DELETE]

+ Request Bad

    + Headers

            Access-Token: notvalidtoken
            Client: abcdefghijklmnopqrstuv
            Uid: isaac.grady@hilpert-reichel.name

+ Response 404 ()

    + Body

            {
              "error": "User was not found or was not logged in."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: rolf_labadie@hahn.info

+ Response 200 ()

    + Body

            {
              "success": true
            }

# Group Settings

## Must Update [api/v1/settings/must_update]

### Get [GET]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: benito_collier@durgan.com

+ Response 200 ()

    + Body

            {
              "must_update": true
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: nisha_howe@lueilwitz.org

+ Response 200 ()

    + Body

            {
              "must_update": false
            }

# Group Status

## Status [api/v1/status]

### Get [GET]

+ Request Ok

+ Response 200 ()

    + Body

            {
              "online": true
            }

# Group Users

## Create User [api/v1/users]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: leandro.lehner@stracke-murray.co

    + Body

            {"user":{"email":"not-valid","password":"VhYo54FhRf8330I","username":"armando","first_name":"Andreas Doyle","last_name":"Morissette","uid":"91549740-b951-4439-bb9b-6487e6761ebf"},"format":"json"}

+ Response 422 ()

    + Body

            {
              "status": "error",
              "data": {
                "id": null,
                "email": "not-valid",
                "allow_password_change": false,
                "first_name": "Andreas Doyle",
                "last_name": "Morissette",
                "username": "armando",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "created_at": null,
                "updated_at": null,
                "provider": "email",
                "uid": "not-valid"
              },
              "errors": {
                "email": [
                  "is not an email"
                ],
                "full_messages": [
                  "Email is not an email"
                ]
              }
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: nathaniel@schamberger.com

    + Body

            {"user":{"email":"geoffrey.crooks@shields.biz","password":"YcMxO7395jBxGgD7","username":"gavin","first_name":"Fritz Quigley","last_name":"Schneider","uid":"bf039ef9-386f-4fdd-a1a8-086539380912"},"format":"json"}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712940195
            uid: geoffrey.crooks@shields.biz

    + Body

            {
              "user": {
                "id": 13,
                "email": "geoffrey.crooks@shields.biz",
                "name": "Fritz Quigley Schneider",
                "username": "gavin",
                "first_name": "Fritz Quigley",
                "last_name": "Schneider",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "uid": "geoffrey.crooks@shields.biz",
                "provider": "email",
                "created_at": "2022-04-12T16:43:15.578Z",
                "updated_at": "2022-04-12T16:43:15.637Z"
              }
            }

## Show User [api/v1/user]

### Show [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: leonore@dubuque.biz

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712940195
            uid: leonore@dubuque.biz

    + Body

            {
              "user": {
                "id": 15,
                "email": "leonore@dubuque.biz",
                "name": "Hilda Konopelski Wintheiser",
                "username": "mechelle",
                "first_name": "Hilda Konopelski",
                "last_name": "Wintheiser",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "uid": "leonore@dubuque.biz",
                "provider": "email",
                "created_at": "2022-04-12T16:43:15.758Z",
                "updated_at": "2022-04-12T16:43:15.819Z"
              }
            }

## Update User [api/v1/user]

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: richard.okuneva@graham.com

    + Body

            {"user":{"username":"new username"}}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1712940196
            uid: richard.okuneva@graham.com

    + Body

            {
              "user": {
                "id": 16,
                "email": "richard.okuneva@graham.com",
                "name": "Amb. Debrah Weber Lindgren",
                "username": "new username",
                "first_name": "Amb. Debrah Weber",
                "last_name": "Lindgren",
                "phone_no": "",
                "address": "",
                "profile_pic": null,
                "uid": "richard.okuneva@graham.com",
                "provider": "email",
                "created_at": "2022-04-12T16:43:15.941Z",
                "updated_at": "2022-04-12T16:43:16.085Z"
              }
            }
