json.id         exam.id
json.access_key exam.access_key
json.name       exam.name
json.active     exam.active
json.start_time exam.start_time
json.end_time   exam.end_time
json.security   exam.security
json.status     exam.status
json.created_at exam.created_at
json.updated_at exam.updated_at
